name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: e-jerk/.github/workflows/ci.yml@main
    with:
      binary_name: grep
      macos_test_script: |
        echo "hello world" > test.txt
        $BINARY --cpu hello test.txt
      linux_test_script: |
        echo "hello world" > test.txt
        $BINARY --cpu hello test.txt
